version: "3.8"

services:
  api:
    build:
      context: ./apps/api
    environment:
      DATABASE_URL: "file:./dev.db"
    volumes:
      - ./apps/api/prisma/dev.db:/app/prisma/dev.db
    ports:
      - 3000:3000

  web:
    build:
      context: ./apps/web
    ports:
      - 8080:80

  redocly:
    image: redocly/redoc
    environment:
      SPEC_URL: http://api:3000/docs-json
    ports:
      - 5050:80